version: 2
updates:
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "puppeteer"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-scripts"
      - dependency-name: "reactstrap"
      - dependency-name: "jest"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/express-server"
    schedule:
      interval: "daily"
    ignore:
      - dependency-name: "express"
      - dependency-name: "cors"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "daily"
    target-branch: "deploy"
    ignore:
      - dependency-name: "puppeteer"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-scripts"
      - dependency-name: "reactstrap"
      - dependency-name: "jest"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/express-server"
    schedule:
      interval: "daily"
    target-branch: "deploy"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "cors"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/front-end"
    schedule:
      interval: "daily"
    target-branch: "batch"
    ignore:
      - dependency-name: "puppeteer"
      - dependency-name: "react"
      - dependency-name: "react-dom"
      - dependency-name: "react-scripts"
      - dependency-name: "reactstrap"
      - dependency-name: "jest"
      - dependency-name: "eslint"
  - package-ecosystem: "npm"
    directory: "/express-server"
    schedule:
      interval: "daily"
    target-branch: "batch"  
    ignore:
      - dependency-name: "express"
      - dependency-name: "cors" 
      - dependency-name: "eslint"     
